#ifndef SOLVING_EQUATIONS_HALFDIVIDE_SOLVING_EQUATIONS_H
#define SOLVING_EQUATIONS_HALFDIVIDE_SOLVING_EQUATIONS_H

#include "equations.h"

class all;

class HalfDivide : all;

#endif //SOLVING_EQUATIONS_HALFDIVIDE_SOLVING_EQUATIONS_H
